In [4]:
import numpy as np

In [5]:
dizi=np.arange(1,24)

In [6]:
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [7]:
dizi.dtype

dtype('int32')

In [8]:
başkaDizi = np.array(["ayşe", "fatma", "sena","ahmet"])

In [9]:
başkaDizi

array(['ayşe', 'fatma', 'sena', 'ahmet'], dtype='<U5')

In [10]:
başkaDizi.shape # dizideki eleman sayısını verir

(4,)

In [11]:
başkaDizi.reshape((2,2))

array([['ayşe', 'fatma'],
       ['sena', 'ahmet']], dtype='<U5')

In [12]:
başkaDizi.dtype

dtype('<U5')

In [13]:
başkaDizi.reshape((2,2)).shape # matriksin kaça kaç olduğunu veriyor ilki sütun ikincisi satır

(2, 2)

In [14]:
x = başkaDizi.reshape((4,1))

In [15]:
x

array([['ayşe'],
       ['fatma'],
       ['sena'],
       ['ahmet']], dtype='<U5')

In [16]:
x.shape

(4, 1)

In [17]:
y = np.identity(3) # identity köşegen matriks oluşturuyor

In [18]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
y.dtype # varsayılan değerler yani default değereler float tipindedir

dtype('float64')

In [20]:
# istediğimiz zaman bu default değerlerin tipini değiştirebiliriz.
y = np.identity(3 ,np.int64)

In [21]:
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

## İNDEX AND SLİCE

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
a # row 0,1,2 ve column 0,1,2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a[(1,1)] # (ROW,COLUMN)

5

In [25]:
a[(2,1)]

8

In [26]:
a[(1,-1)] # birinci satırın son elemanı

6

In [27]:
a[0,1:] # sıfırıncı satırda birinci sütundan sonuna kadar

array([2, 3])

In [28]:
a[1,0:]

array([4, 5, 6])

In [29]:
b =np.array([1,2,3,4,5,6,7,8,9]) # boolenları dizlerde kullanbiliriz

In [30]:
type(b)

numpy.ndarray

In [31]:
c = b<5

In [32]:
c

array([ True,  True,  True,  True, False, False, False, False, False])

In [33]:
print(b[c]) # b dizisindeki c'yi sağlayan elemanları liste şeklinde döndürür

[1 2 3 4]


In [34]:
type(b[c])

numpy.ndarray

## MATRİX

In [35]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [36]:
benimMatrixDizim = np.array(benimListem)

In [37]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [38]:
benimMatrixDizim[0]

array([10, 20, 30])

In [39]:
benimMatrixDizim[1][2]

40

In [40]:
benimMatrixDizim[1,2]

40

In [41]:
benimMatrixDizim[2:,2:]

array([[60]])

In [42]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [43]:
yeniMatrix = np.array(yeniListe)

In [44]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])