# Bir lineer cebir kütüphanesi

In [1]:
import numpy as np

In [2]:
# numpy array

In [3]:
benimListem = [10,20,30,40]

In [4]:
np.array(benimListem)

array([10, 20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
# type numpy dizisi olarak döndürüyor

In [7]:
matrixListesi = [[10,20,30],[40,50,60],[70,80,90]]

In [8]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
# liste içindeki listeleri numpyda matrix olarak yani iki boyutlu dizi olarak döndürüyor.

# NUMPY METODLARI 

In [10]:
# ARANGE

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)
# üçüncü veri step size

array([0, 2, 4, 6, 8])

In [14]:
#zeros= elemanları sıfır olan numpy dizisi çıkarır

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
#linspace = ilk veriden başlayıp ikinci veriye kadar sabit farkla(üçüncü veri) artan numpy dizisi oluşturur.

In [20]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [21]:
np.linspace(0,20,36)

array([ 0.        ,  0.57142857,  1.14285714,  1.71428571,  2.28571429,
        2.85714286,  3.42857143,  4.        ,  4.57142857,  5.14285714,
        5.71428571,  6.28571429,  6.85714286,  7.42857143,  8.        ,
        8.57142857,  9.14285714,  9.71428571, 10.28571429, 10.85714286,
       11.42857143, 12.        , 12.57142857, 13.14285714, 13.71428571,
       14.28571429, 14.85714286, 15.42857143, 16.        , 16.57142857,
       17.14285714, 17.71428571, 18.28571429, 18.85714286, 19.42857143,
       20.        ])

In [22]:
#eye= aydentity matrix(köşegen matriks)oluşturmak için kullanılır

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
# random kütüphanesi= rasgele sayılardan oluşan numpy dizisi oluşturuyor

In [25]:
np.random.randn(8)

array([-1.09977433, -2.38833957,  0.54980952,  0.00987603,  0.54474114,
        1.19621403,  1.31678585, -0.37230598])

In [26]:
np.random.randn(4,4)

array([[-1.11488158, -0.14533683,  0.7210002 , -1.33619314],
       [ 0.137804  , -0.53609731, -1.43317936,  0.92292204],
       [ 1.77147884,  2.33481983, -0.3216648 ,  0.00258396],
       [ 0.59933109, -0.59251182,  0.71091933,  1.4202255 ]])

In [27]:
np.random.randint(1,10)
#rastgele değerler veriyor

2

In [28]:
np.random.randint(1,300,5)
# 1 ile 300 arasından rastgele seçilen beş değer ile bir numpy dizisi oluştur

array([176, 119,  34, 252,  83])

In [29]:
#bir değişkene eşitleyebilirdik

In [30]:
benimNumpyDizim = np.arange(1,10)

In [31]:
benimNumpyDizim

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#Numpy dizimetodları

In [33]:
benimReshapeDizim = benimNumpyDizim.reshape(3,3)
# reshape numpy dizilerini matrikse dönüştürür.

In [34]:
#dizi içerisindeki min ve max değerleri bulmak
benimNumpyDizim.max()

9

In [35]:
benimNumpyDizim.min()

1

In [36]:
#max ve min değerlerinin indekslerini de bulabiliriz.4
benimNumpyDizim.argmax()

8

In [37]:
benimNumpyDizim.argmin()

0

In [38]:
benimNumpyDizim.shape

(9,)

In [39]:
benimReshapeDizim.shape

(3, 3)

In [40]:
#shape ise dizinin şeklini veriyor 

# NUMPY İNDEKSLER

In [41]:
benimDizim = np.arange(0,15)

In [42]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
benimDizim[5]

5

In [44]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [45]:
benimDizim[3:8]=-5
#benimDizim[3:8] dizisinin elemanlarını -5 e eşitliyor

In [46]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [56]:
başkaDizi=np.arange(0,24)

In [3]:
başkaDizi

NameError: name 'başkaDizi' is not defined

In [57]:
başkaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
slicingDizisi = başkaDizi[6:12]

In [59]:
slicingDizisi

array([ 6,  7,  8,  9, 10, 11])

In [60]:
slicingDizisi[:] = 700

In [61]:
slicingDizisi

array([700, 700, 700, 700, 700, 700])

In [62]:
başkaDizi

array([  0,   1,   2,   3,   4,   5, 700, 700, 700, 700, 700, 700,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [63]:
# numpy dizilerinden bir parça alır ve sonra bunun üzerinde değişiklikler yaparsanız bu değişiklikler parça aldığınız ana dizinizde de meydzna gelir

In [64]:
# eğer ana dizinin yaptığın değişikliklerden etkilenmesini istemiyorsan dizinin .copy() ile yeni bir kopyasını oluşturacak ve kopyası üzerinde işlem yapacaksın

In [66]:
dizi = np.arange(0,24)

In [67]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
kopyaDizi = dizi.copy()

In [70]:
kopyaDizi.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [71]:
kopyaDizi[3:5] = 0

In [72]:
kopyaDizi

array([ 0,  1,  2,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## operation

In [74]:
yeniDizi=np.random.randint(0,100,20)

In [75]:
yeniDizi

array([91, 64, 99, 32, 66, 46, 66, 43, 25, 48, 90, 26, 55,  4, 42, 92, 55,
       64, 69, 80])

In [76]:
a = yeniDizi > 24

In [77]:
a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [80]:
yeniDizi[a]# indeks verir gibi dizinin içine a dizisini koyarsak a dizisinin true eleman değerlerini döndürür

array([91, 64, 99, 32, 66, 46, 66, 43, 25, 48, 90, 26, 55, 42, 92, 55, 64,
       69, 80])

In [81]:
yeniDizi + yeniDizi

array([182, 128, 198,  64, 132,  92, 132,  86,  50,  96, 180,  52, 110,
         8,  84, 184, 110, 128, 138, 160])

In [82]:
yeniDizi - yeniDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
yeniDizi*yeniDizi

array([8281, 4096, 9801, 1024, 4356, 2116, 4356, 1849,  625, 2304, 8100,
        676, 3025,   16, 1764, 8464, 3025, 4096, 4761, 6400])

In [84]:
yeniDizi/yeniDizi

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [85]:
np.sqrt(yeniDizi)

array([9.53939201, 8.        , 9.94987437, 5.65685425, 8.1240384 ,
       6.78232998, 8.1240384 , 6.55743852, 5.        , 6.92820323,
       9.48683298, 5.09901951, 7.41619849, 2.        , 6.4807407 ,
       9.59166305, 7.41619849, 8.        , 8.30662386, 8.94427191])

In [86]:
np.sum(yeniDizi)

1157

In [88]:
np.min(yeniDizi)

4

In [89]:
np.max(yeniDizi)

99